### ISSUE TITLE
USER STORY: Admin Login

### ISSUE THREAD

**Issue by RicardoIT-Web** [RicardoIT-Web/dine_with_me#1]
As an **administrator** I can **click on the navbar and select "login"** so that I can **access the admin environment**

## Acceptance Criteria
1. Identify navbar on the home page
2. Click on login

## Tasks
- [ ] Create HTML and CSS - Home page
- [ ] Create HTML and CSS - login page
- [ ] Create models and views for admin environment

**Comment by RicardoIT-Web** [comment]
1st issue to get the basics in place
